import { Car } from "./types";

export const CARS: Car[] = [
  {
    id: "maruti-brezza-2024",
    name: "Maruti Brezza",
    brand: "Maruti",
    model: "Brezza",
    year: 2024,
    price: 899000,
    image: "/cars/brezza.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 19.8,
    seating: 5,
    engineCC: 1462,
    power: 103,
    torque: 137,
    airbags: 6,
    rating: 4.2,
    pros: ["Best-in-class mileage", "Low maintenance", "Wide service network"],
    cons: ["No 4WD option", "Slightly small boot"],
    tags: ["City", "Family"],
  },
  {
    id: "tata-nexon-ev-2024",
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV",
    year: 2024,
    price: 1399000,
    image: "/cars/nexon-ev.jpg",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 0,
    seating: 5,
    engineCC: 0,
    power: 143,
    torque: 250,
    airbags: 6,
    rating: 4.4,
    pros: ["₹0 fuel cost", "Smooth drive", "5-star NCAP safety"],
    cons: ["Charging infrastructure limited", "Long charge time"],
    tags: ["City", "Highway"],
  },
  {
    id: "hyundai-creta-2024",
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2024,
    price: 1100000,
    image: "/cars/creta.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 17.0,
    seating: 5,
    engineCC: 1497,
    power: 115,
    torque: 144,
    airbags: 6,
    rating: 4.3,
    pros: ["Premium interior", "Feature-loaded", "Panoramic sunroof"],
    cons: ["Price premium vs rivals", "Turbo variant pricey"],
    tags: ["City", "Family", "Highway"],
  },
  {
    id: "maruti-swift-2024",
    name: "Maruti Swift",
    brand: "Maruti",
    model: "Swift",
    year: 2024,
    price: 699000,
    image: "/cars/swift.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileage: 24.8,
    seating: 5,
    engineCC: 1197,
    power: 82,
    torque: 112,
    airbags: 2,
    rating: 4.0,
    pros: ["Excellent fuel economy", "Fun to drive", "Low cost"],
    cons: ["Rear space tight", "Basic features"],
    tags: ["City", "Budget"],
  },
  {
    id: "honda-city-2024",
    name: "Honda City",
    brand: "Honda",
    model: "City",
    year: 2024,
    price: 1200000,
    image: "/cars/city.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    mileage: 18.3,
    seating: 5,
    engineCC: 1498,
    power: 121,
    torque: 145,
    airbags: 6,
    rating: 4.3,
    pros: ["Spacious cabin", "Refined engine", "Good resale value"],
    cons: ["No sunroof in base", "Ground clearance low"],
    tags: ["City", "Highway", "Family"],
  },
  {
    id: "mahindra-scorpio-n-2024",
    name: "Mahindra Scorpio N",
    brand: "Mahindra",
    model: "Scorpio N",
    year: 2024,
    price: 1350000,
    image: "/cars/scorpio-n.jpg",
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 15.2,
    seating: 7,
    engineCC: 2184,
    power: 174,
    torque: 400,
    airbags: 6,
    rating: 4.5,
    pros: ["Powerful diesel", "7-seater", "4WD option", "5-star NCAP"],
    cons: ["NVH could be better", "Large footprint for city"],
    tags: ["Highway", "Off-road", "Family"],
  },
  {
    id: "toyota-innova-crysta-2024",
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2024,
    price: 2000000,
    image: "/cars/innova.jpg",
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "MPV",
    mileage: 14.8,
    seating: 8,
    engineCC: 2393,
    power: 148,
    torque: 343,
    airbags: 7,
    rating: 4.6,
    pros: ["Legendary reliability", "8-seater", "Resale king"],
    cons: ["Expensive price", "No petrol auto"],
    tags: ["Family", "Highway"],
  },
  {
    id: "kia-seltos-2024",
    name: "Kia Seltos",
    brand: "Kia",
    model: "Seltos",
    year: 2024,
    price: 1050000,
    image: "/cars/seltos.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 16.5,
    seating: 5,
    engineCC: 1497,
    power: 115,
    torque: 144,
    airbags: 6,
    rating: 4.3,
    pros: ["360 camera", "Large touchscreen", "Build quality"],
    cons: ["Expensive top variants", "Boot space average"],
    tags: ["City", "Highway"],
  },
  {
    id: "tata-punch-2024",
    name: "Tata Punch",
    brand: "Tata",
    model: "Punch",
    year: 2024,
    price: 625000,
    image: "/cars/punch.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "SUV",
    mileage: 20.1,
    seating: 5,
    engineCC: 1199,
    power: 88,
    torque: 115,
    airbags: 2,
    rating: 4.1,
    pros: ["5-star NCAP safety", "SUV stance for less", "Great mileage"],
    cons: ["Small engine", "Limited features base"],
    tags: ["City", "Budget"],
  },
  {
    id: "volkswagen-virtus-2024",
    name: "Volkswagen Virtus",
    brand: "Volkswagen",
    model: "Virtus",
    year: 2024,
    price: 1150000,
    image: "/cars/virtus.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Sedan",
    mileage: 19.4,
    seating: 5,
    engineCC: 1498,
    power: 150,
    torque: 250,
    airbags: 6,
    rating: 4.4,
    pros: ["European build quality", "Punchy 1.5 TSI", "Best-in-class handling"],
    cons: ["Expensive service", "Boot lip high"],
    tags: ["Highway", "City"],
  },
];

export const USED_CARS: Car[] = [
  {
    id: "used-swift-2021",
    name: "Maruti Swift",
    brand: "Maruti",
    model: "Swift",
    year: 2021,
    price: 500000,
    image: "/cars/swift.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileage: 22.0,
    seating: 5,
    engineCC: 1197,
    power: 82,
    torque: 112,
    airbags: 2,
    rating: 3.9,
    pros: ["Low price", "Low km driven"],
    cons: ["Older model"],
    tags: ["City", "Budget"],
    isUsed: true,
    kmDriven: 32000,
    owners: 1,
  },
  {
    id: "used-creta-2022",
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2022,
    price: 950000,
    image: "/cars/creta.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 16.5,
    seating: 5,
    engineCC: 1497,
    power: 115,
    torque: 144,
    airbags: 6,
    rating: 4.2,
    pros: ["Well-maintained", "Single owner", "Full service history"],
    cons: ["2 years old"],
    tags: ["City", "Family"],
    isUsed: true,
    kmDriven: 28000,
    owners: 1,
  },
  {
    id: "used-innova-2020",
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2020,
    price: 1600000,
    image: "/cars/innova.jpg",
    fuelType: "Diesel",
    transmission: "Manual",
    bodyType: "MPV",
    mileage: 14.0,
    seating: 8,
    engineCC: 2393,
    power: 148,
    torque: 343,
    airbags: 7,
    rating: 4.5,
    pros: ["Excellent reliability", "Low operational cost"],
    cons: ["Higher km driven"],
    tags: ["Family", "Highway"],
    isUsed: true,
    kmDriven: 65000,
    owners: 1,
  },
];

// ---------------------------------------------------------------------------
// VARIANT CATALOGUE
// Multiple variants of the same base model for "Compare Same Car Variants"
// ---------------------------------------------------------------------------

export const CAR_VARIANTS: Car[] = [
  // ── Hyundai Creta ──────────────────────────────────────────────────────
  {
    id: "creta-e-petrol-mt",
    name: "Hyundai Creta E Petrol MT",
    brand: "Hyundai",
    model: "Creta",
    variant: "E Petrol MT",
    year: 2024,
    price: 1099000,
    image: "/cars/creta.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "SUV",
    mileage: 17.4,
    seating: 5,
    engineCC: 1497,
    power: 115,
    torque: 144,
    airbags: 6,
    rating: 4.0,
    pros: ["Lowest price entry", "Best mileage in Creta range"],
    cons: ["No sunroof", "Manual only", "Less features"],
    tags: ["City", "Budget"],
  },
  {
    id: "creta-s-petrol-at",
    name: "Hyundai Creta S Petrol AT",
    brand: "Hyundai",
    model: "Creta",
    variant: "S Petrol AT",
    year: 2024,
    price: 1295000,
    image: "/cars/creta.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 17.0,
    seating: 5,
    engineCC: 1497,
    power: 115,
    torque: 144,
    airbags: 6,
    rating: 4.3,
    pros: ["Auto transmission", "Good features", "Sunroof"],
    cons: ["Slightly lower mileage vs MT", "Mid-range price"],
    tags: ["City", "Family"],
  },
  {
    id: "creta-sx-diesel-at",
    name: "Hyundai Creta SX Diesel AT",
    brand: "Hyundai",
    model: "Creta",
    variant: "SX Diesel AT",
    year: 2024,
    price: 1650000,
    image: "/cars/creta.jpg",
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 21.4,
    seating: 5,
    engineCC: 1493,
    power: 115,
    torque: 250,
    airbags: 6,
    rating: 4.4,
    pros: ["Outstanding diesel mileage", "Most torque", "Loaded features"],
    cons: ["Expensive", "Diesel NVH"],
    tags: ["Highway", "Family"],
  },
  {
    id: "creta-sxo-turbo-petrol-dct",
    name: "Hyundai Creta SX(O) Turbo Petrol DCT",
    brand: "Hyundai",
    model: "Creta",
    variant: "SX(O) Turbo Petrol DCT",
    year: 2024,
    price: 1950000,
    image: "/cars/creta.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 16.8,
    seating: 5,
    engineCC: 1482,
    power: 158,
    torque: 253,
    airbags: 6,
    rating: 4.6,
    pros: ["Sporty turbo engine", "Panoramic sunroof", "ADAS", "Best in class features"],
    cons: ["Most expensive Creta", "Lower mileage"],
    tags: ["City", "Highway"],
  },
  // ── Tata Nexon EV ──────────────────────────────────────────────────────
  {
    id: "nexon-ev-medium-range",
    name: "Tata Nexon EV Medium Range",
    brand: "Tata",
    model: "Nexon EV",
    variant: "Medium Range (45 kWh)",
    year: 2024,
    price: 1399000,
    image: "/cars/nexon-ev.jpg",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 0,
    seating: 5,
    engineCC: 0,
    power: 143,
    torque: 250,
    airbags: 6,
    rating: 4.3,
    pros: ["Accessible price", "Good city range", "5-star safety"],
    cons: ["Smaller battery", "AC range drops significantly"],
    tags: ["City", "Highway"],
  },
  {
    id: "nexon-ev-long-range",
    name: "Tata Nexon EV Long Range",
    brand: "Tata",
    model: "Nexon EV",
    variant: "Long Range (60 kWh)",
    year: 2024,
    price: 1799000,
    image: "/cars/nexon-ev.jpg",
    fuelType: "Electric",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 0,
    seating: 5,
    engineCC: 0,
    power: 167,
    torque: 280,
    airbags: 6,
    rating: 4.5,
    pros: ["500+ km range", "Fast charge support", "More power"],
    cons: ["₹4L more than MR", "Heavier battery"],
    tags: ["City", "Highway"],
  },
  // ── Maruti Swift ───────────────────────────────────────────────────────
  {
    id: "swift-lxi-petrol-mt",
    name: "Maruti Swift LXi Petrol MT",
    brand: "Maruti",
    model: "Swift",
    variant: "LXi Petrol MT",
    year: 2024,
    price: 647000,
    image: "/cars/swift.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileage: 24.8,
    seating: 5,
    engineCC: 1197,
    power: 82,
    torque: 112,
    airbags: 2,
    rating: 3.9,
    pros: ["Most affordable Swift", "Highest mileage"],
    cons: ["Basic features", "Only 2 airbags"],
    tags: ["City", "Budget"],
  },
  {
    id: "swift-vxi-petrol-mt",
    name: "Maruti Swift VXi Petrol MT",
    brand: "Maruti",
    model: "Swift",
    variant: "VXi Petrol MT",
    year: 2024,
    price: 730000,
    image: "/cars/swift.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileage: 24.8,
    seating: 5,
    engineCC: 1197,
    power: 82,
    torque: 112,
    airbags: 6,
    rating: 4.1,
    pros: ["6 airbags", "Touchscreen", "360 camera"],
    cons: ["Manual only in this trim"],
    tags: ["City", "Budget"],
  },
  {
    id: "swift-zxi-plus-cng",
    name: "Maruti Swift ZXi+ CNG",
    brand: "Maruti",
    model: "Swift",
    variant: "ZXi+ CNG",
    year: 2024,
    price: 860000,
    image: "/cars/swift.jpg",
    fuelType: "CNG",
    transmission: "Manual",
    bodyType: "Hatchback",
    mileage: 32.85,
    seating: 5,
    engineCC: 1197,
    power: 69,
    torque: 95,
    airbags: 6,
    rating: 4.0,
    pros: ["Best-in-class CNG mileage", "Low running cost"],
    cons: ["Boot space reduced by CNG kit", "Slightly less power"],
    tags: ["City", "Budget"],
  },
  {
    id: "swift-zxi-plus-at",
    name: "Maruti Swift ZXi+ AT",
    brand: "Maruti",
    model: "Swift",
    variant: "ZXi+ Petrol AT",
    year: 2024,
    price: 895000,
    image: "/cars/swift.jpg",
    fuelType: "Petrol",
    transmission: "Automatic",
    bodyType: "Hatchback",
    mileage: 22.1,
    seating: 5,
    engineCC: 1197,
    power: 82,
    torque: 112,
    airbags: 6,
    rating: 4.2,
    pros: ["Auto gearbox", "Full features", "Fun to drive"],
    cons: ["Top price Swift", "Slight mileage drop vs MT"],
    tags: ["City"],
  },
  // ── Mahindra Scorpio N ──────────────────────────────────────────────────
  {
    id: "scorpio-n-z2-petrol-mt",
    name: "Mahindra Scorpio N Z2 Petrol MT",
    brand: "Mahindra",
    model: "Scorpio N",
    variant: "Z2 Petrol MT",
    year: 2024,
    price: 1349000,
    image: "/cars/scorpio-n.jpg",
    fuelType: "Petrol",
    transmission: "Manual",
    bodyType: "SUV",
    mileage: 15.2,
    seating: 6,
    engineCC: 1997,
    power: 200,
    torque: 380,
    airbags: 6,
    rating: 4.3,
    pros: ["Powerful petrol", "Entry price", "6-seater"],
    cons: ["No 4WD", "Less features"],
    tags: ["City", "Highway"],
  },
  {
    id: "scorpio-n-z8-diesel-at-4wd",
    name: "Mahindra Scorpio N Z8 Diesel AT 4WD",
    brand: "Mahindra",
    model: "Scorpio N",
    variant: "Z8 Diesel AT 4WD",
    year: 2024,
    price: 2499000,
    image: "/cars/scorpio-n.jpg",
    fuelType: "Diesel",
    transmission: "Automatic",
    bodyType: "SUV",
    mileage: 15.2,
    seating: 7,
    engineCC: 2184,
    power: 174,
    torque: 400,
    airbags: 6,
    rating: 4.6,
    pros: ["Real 4WD off-road", "7-seater", "5-star NCAP", "All bells & whistles"],
    cons: ["Expensive", "Large city footprint"],
    tags: ["Highway", "Off-road", "Family"],
  },
];
